### ISSUE TITLE
조도센싱

### ISSUE THREAD

**Issue by kairos03** [Dcom-KHU/2018-2-smart-light#2]
- [x] 회로 연결
  - [x] 라즈베리파이 연결 테스트
  - [x] 라즈베리파이, 조도센서 연결 테스트
 
- postSur()
  - [x] aws iot 에서 thing만들기
  - [x] aws shadow 로 상태 publish 하기
  - [ ] https://github.com/aws/aws-iot-device-sdk-python 사용하기

**Comment by jju0807** [comment]
각 항목 설명좀 달아주세요
