### ISSUE TITLE
전구 밝기 계산 알고리즘

### ISSUE THREAD

**Issue by kairos03** [Dcom-KHU/2018-2-smart-light#9]
- [ ] calBrightness()
  - n개의 조도센서에서 얻어온 조도값으로 m개의 전구 밝기 계산

**Comment by jju0807** [comment]
![image](https://user-images.githubusercontent.com/31975378/49248755-d061b400-f45d-11e8-83d7-9c65cb5f5724.png)

**Comment by jju0807** [comment]
![image](https://user-images.githubusercontent.com/31975378/49248804-ea9b9200-f45d-11e8-87fd-3ec4dcb20cd5.png)


[질문]
1. 공간 전체를 같은 밝기로 조절한다고 할 때, 결국 최종 조명A, B, C의 밝기는 같아져야 공간 전체 밝기도 같아짐
2. Lambda 함수의 출력값은 조명 A, B, C의 밝기인지? 아니면 A, B, C가 얼마나 바뀌어야 할 변화량인지?
